### ISSUE TITLE
Plano de Iteração

### ISSUE THREAD

**Issue by v1d3rm3** [ccsa-ufrn/manual-do-aluno#1]
Plano de Iteração - 1.0.1

- [x] ~~Validar aplicativo com Késia~~. #2 
- [ ] Criar conta no Google Play Store #7
- [x] ~~Verificar a questão de gerar uma build para iOS~~ #5 (Volta para o Backlog)
    - [x] ~~Caso seja possível o de cima, criar uma conta na Apple Store~~. ( **-** )
- [x] ~~Compactar imagens do Aplicativo~~ #4 
- [x] ~~Correção de Bugs~~: #3, #6 

Atualização após reunião com Késia
- [ ] Alteração do ícone #8
- [ ] Alteração da splashscreen #9
- [ ] Criação de uma área para CA #10 (**pendente**)
- [x] ~~Reunião com Jéssica do NADis~~

**Comment by mrmorais** [comment]
#### Sobre a reunião com Jessyca
Jessyca está criando a nova splashscreen do app, e solicitou que seja inserido um card exclusivo para o NADis. Sobre o ícone ela disse que depois de feita a capa podemos avaliar se a capa e o ícone serão os mesmos, caso não caia bem utilizaremos a logo do CCSA.
